_wandb:
    value:
        cli_version: 0.19.1
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 55
                - 86
                - 95
                - 105
            "2":
                - 55
                - 86
                - 92
                - 95
                - 105
            "3":
                - 2
                - 16
                - 23
                - 55
            "4": 3.10.12
            "5": 0.19.1
            "8":
                - 5
            "12": 0.19.1
            "13": linux-x86_64
chunk_overlap:
    value: 100
chunk_size:
    value: 400
docs_dir:
    value: ../documentos_base
prompt_file:
    value: chat_prompt.json
vector_store:
    value: ./vector_store
wandb_project:
    value: daphane
